fix: add message attribute data type
Existing SNS submissions are being rejected with
com.amazonaws.services.sns.model.AmazonSNSException: 1 validation error
detected: Value null at 'messageAttributes.event_type.member.dataType'
failed to satisfy constraint: Member must not be null (Service:
AmazonSNS; Status Code: 400; Error Code: ValidationError; Request ID:
184a5270-db58-51bb-a5da-0fe407247ce4; Proxy: null)

I cannot replicate this locally, so this is a slightly speculative fix.

NO-TICKET